name: SyntaLinker
channels:
  - rdkit
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _anaconda_depends=2019.03=py36_0
  - anaconda=custom=py36_1
  - anaconda-client=1.6.14=py36_0
  - anaconda-navigator=1.8.7=py36_0
  - anaconda-project=0.8.2=py36h44fb852_0
  - babel=2.5.3=py36_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.11.28=py36_1
  - conda=4.8.3=py36_0
  - conda-build=3.10.5=py36_0
  - conda-env=2.6.0=h36134e3_1
  - conda-package-handling=1.6.0=py36h7b6447c_0
  - conda-verify=2.0.0=py36h98955d8_0
  - cython=0.28.2=py36h14c3975_0
  - cytoolz=0.9.0.1=py36h14c3975_0
  - dbus=1.13.2=h714fa37_1
  - distributed=1.21.8=py36_0
  - docopt=0.6.2=py36_0
  - docutils=0.14=py36hb0f60f5_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h5a9c865_0
  - imagesize=1.0.0=py36_0
  - importlib_metadata=1.5.0=py36_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36he59e554_1
  - jupyter_core=4.4.0=py36h7c827e3_0
  - jupyterlab=0.32.1=py36_0
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.37=hbc83047_0
  - libtool=2.4.6=h544aabb_3
  - matplotlib=3.1.1=py36h5429711_0
  - mkl=2018.0.2=1
  - mkl-service=1.1.2=py36h17a0993_4
  - mkl_fft=1.0.1=py36h3010b51_0
  - mkl_random=1.0.1=py36h629b387_0
  - more-itertools=4.1.0=py36_0
  - multipledispatch=0.5.0=py36_0
  - notebook=5.5.0=py36_0
  - numexpr=2.6.5=py36h7bf3b9c_0
  - numpydoc=0.8.0=py36_0
  - packaging=17.1=py36_0
  - pandas=0.25.3=py36he6710b0_0
  - path.py=11.0.1=py36_0
  - pathlib2=2.3.2=py36_0
  - pickleshare=0.7.4=py36h63277f8_0
  - pillow=6.2.1=py36h34e0f95_0
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h7b6447c_0
  - pkginfo=1.4.2=py36_1
  - pluggy=0.6.0=py36hb689045_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - psutil=5.4.5=py36h14c3975_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - py=1.5.3=py36_0
  - py-boost=1.67.0=py36h04863e7_4
  - pyparsing=2.2.0=py36hee85983_1
  - pyqt=5.9.2=py36h751905a_0
  - pyrsistent=0.16.0=py36h7b6447c_0
  - pysocks=1.6.8=py36_0
  - pytables=3.4.3=py36h02b9ad4_2
  - pytest=3.5.1=py36_0
  - pytest-openfiles=0.3.0=py36_0
  - python=3.6.10=h191fe78_1
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - rdkit=2019.09.2.0=py36hc20afe1_1
  - readline=7.0=ha6073c6_4
  - scipy=1.1.0=py36hfc37229_0
  - seaborn=0.8.1=py36hfad7ec4_0
  - six=1.13.0=py36_0
  - sqlite=3.31.1=h7b6447c_0
  - pip:
    - joblib==0.14.1
    - torch==1.3.1
    - torchtext==0.4.0
    - tqdm==4.30.0
